service: node-event-example
provider:
  name: scaleway
  runtime: node20

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node-modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    handler: handler.handle
    events:
      - schedule:
          rate: '1 * * * *'
          input:
            field-a: "some-string"
            field-b: 1234
