service: node-event-example
configValidationMode: off
provider:
  name: scaleway
  runtime: node20

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node-modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    handler: handler.handle
    events:
      - schedule:
          rate: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
          input:
            foo: "some-string"
            bar: 1234
