service: container-event-example

provider:
  name: scaleway

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node-modules/**'
    - '!.gitignore'
    - '!.git/**'

custom:
  containers:
    first:
      directory: container
      events:
        - schedule:
            rate: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
            input:
              field-a: "some value"
              field-b: 1234
